### ISSUE TITLE
Firebase MLについて調べる

### ISSUE THREAD

**Issue by DaigoWakabayashi** [DaigoWakabayashi/nekobuzz#18]
# 公式Doc

- Firebase ML 画像のラベル付け
https://firebase.google.com/docs/ml-kit/label-images?hl=ja

**Comment by daigo-program** [comment]
FirebaseMLの画像ラベル付けについて
https://www.isoroot.jp/blog/1871/

**Comment by daigo-program** [comment]
Qiita記事（Flutterを使っている）
https://qiita.com/kazutxt/items/fb6f122852f114c81486#%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%83%A9%E3%83%99%E3%83%AA%E3%83%B3%E3%82%B0%E3%82%AB%E3%83%A1%E3%83%A9-1

↑で思ったのは、「画面上に表示されているもの」を判別するんじゃないかってこと
そうなった場合、画像つきのバズっているツイートを日本の中で取得→表示時にねこ関係だけフィルタリング
みたいなながれかな

**Comment by daigo-program** [comment]
firebase MLのFlutterパッケージは
- ML Custom
https://pub.dev/packages/firebase_ml_custom

- ML Vision 
https://pub.dev/packages/firebase_ml_vision

の2種類があるが、後者のパッケージ開発がストップしているので、使うとするならMLCustomになりそう

**Comment by DaigoWakabayashi** [comment]
今のところ、SearchAPIだけで結構いい感じなので、画像認識を実装するかどうかも含めて考え直す
一旦close
